- name: Volume operations on powerflex array.
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    gateway_host: '<gatewayIP>'
    port: '443'
    verifycert: False
    username: '<uname>'
    password: '<Pword>'
    protection_domain_name: "PD01"
    storage_pool_name: "SP01"
    snapshot_policy_name: ""
    vol_name: "ansible_test_volume"
    size: "8"
  collections:
    - dellemc.powerflex

  tasks:
  - name: Create a volume, set snapshot policy, and map volume
    register: result
    dellemc.powerflex.volume:
      gateway_host: "{{gateway_host}}"
      username: "{{username}}"
      password: "{{password}}"
      verifycert: "{{verifycert}}"
      vol_name: "{{vol_name}}"
      storage_pool_name: "{{storage_pool_name}}"
      protection_domain_name: "{{protection_domain_name}}"
      snapshot_policy_name: "{{snapshot_policy_name}}"
      sdc:
      - sdc_name: "<sdcIP1>"
      - sdc_name: "<sdcIP2>"
      allow_multiple_mappings: True
      sdc_state: "mapped"
      size: "{{size}}"
      state: "present"

  - name: Set volume id
    set_fact:
      vol_id: "{{result.volume_details.id}}"
 
  - name: Get volume details using volume name
    dellemc.powerflex.volume:
      gateway_host: "{{gateway_host}}"
      username: "{{username}}"
      password: "{{password}}"
      verifycert: "{{verifycert}}"
      vol_name: "{{vol_name}}"
      state: "present"
    register: subset_results_volume

  - debug:
     var: subset_results_volume
