---
# tasks file for pdg-fs-01
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - "{{ groups['primary_domain_controller'][0] }}"
      - "{{ groups['replica_domain_controller'][0] }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required

- name: Create directory multiverse
  ansible.windows.win_file:
    path: C:\shares\multiverse
    state: directory

- name: Add Multiverse Share
  ansible.windows.win_share:
    name: Multiverse
    description: Where we lost everything
    path: C:\shares\multiverse
    list: yes
    full: Administrators