---
# tasks file for pdg-dc-01
- name: Install Active Directory Role 
  win_feature: >
      name=AD-Domain-Services
      include_management_tools=yes
      include_sub_features=yes
      state=present
  register: result
- name: Configure Active Directory Domain
  win_domain: >
    dns_domain_name='{{ domain }}'
    safe_mode_password='{{ domain_safemode_password }}'
  register: ad

- name: Reboot after promotion
  ansible.windows.win_reboot:
  when: ad.reboot_required

- name: Ensure OU is present & protected
  microsoft.ad.ou:
    name: Guardians
    path: DC=winlab,DC=lab
    state: present
    protect_from_deletion: true

- name: Ensure user Groot is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: groot
    password: Gr00tP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Rocket is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: rocket
    password: R0cketP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Nebula is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: groot
    password: NebulaP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Yondu is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: yondu
    password: Y0nduP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Ronan is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: ronan
    password: R0nanP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Thanos is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: thanos
    password: Than0sP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users     

- name: Ensure user Mantis is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: mantis
    password: M@ntisP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users

- name: Ensure user Kraglin is present in OU=Guardians,DC=winlab,DC=lab
  microsoft.ad.user:
    name: kraglin
    password: Kr@glinP4ssw0rd
    state: present
    path: OU=Guardians,DC=winlab,DC=lab
    groups:
      set:
      - Domain Admins
      - Domain Users