variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_datacenter" {}
variable "vsphere_resource_pool" {}
variable "vsphere_datastore" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_network" {}
variable "vsphere_virtual_machine_template" {}
variable "vsphere_virtual_machine_name" {}
variable "vsphere_vm_firmware" {}
variable "vsphere_network_adapter" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "ReplicaDC_name" {}
variable "Fileserver_name" {}
variable "PDC_IP" {}
variable "ReplicaDC_IP" {}
variable "Fileserver_IP" {}
variable "netmask" {}
variable "def_gw" {}
variable "dns_server" {}
variable "PDC_cpu_num" {}
variable "ReplicaDC_cpu_num" {}
variable "Fileserver_cpu_num" {}
variable "PDC_mem" {}
variable "ReplicaDC_mem" {}
variable "Fileserver_mem" {}


